
const StatsSection = () => {
  return (
    <section className="py-16 px-6">
      <div className="max-w-6xl mx-auto text-center">
        <div className="grid grid-cols-2 md:grid-cols-4 gap-8 mb-12">
          <div className="animate-fade-in" style={{ animationDelay: '0.1s' }}>
            <div className="text-3xl font-bold text-orange-400 mb-2 hover:scale-110 transition-transform duration-300" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.8)' }}>1,000+</div>
            <div className="text-white text-sm" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)' }}>Historical Events</div>
          </div>
          <div className="animate-fade-in" style={{ animationDelay: '0.2s' }}>
            <div className="text-3xl font-bold text-orange-400 mb-2 hover:scale-110 transition-transform duration-300" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.8)' }}>300</div>
            <div className="text-white text-sm" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)' }}>Themes</div>
          </div>
          <div className="animate-fade-in" style={{ animationDelay: '0.3s' }}>
            <div className="text-3xl font-bold text-orange-400 mb-2 hover:scale-110 transition-transform duration-300" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.8)' }}>190+</div>
            <div className="text-white text-sm" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)' }}>Countries on 7 continents</div>
          </div>
          <div className="animate-fade-in" style={{ animationDelay: '0.4s' }}>
            <div className="text-3xl font-bold text-orange-400 mb-2 hover:scale-110 transition-transform duration-300" style={{ textShadow: '2px 2px 4px rgba(0,0,0,0.8)' }}>1850 - 2025</div>
            <div className="text-white text-sm" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)' }}>Historical Range</div>
          </div>
        </div>
        
        <div className="text-center space-y-6">
          <p className="text-slate-300 text-sm animate-fade-in" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)', animationDelay: '0.5s' }}>
            Historical events and images are curated and generated by AI
          </p>
          <p className="text-slate-300 text-sm animate-fade-in" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)', animationDelay: '0.6s' }}>
            Coming soon: -2500 to 1850
          </p>
          
          <div className="max-w-md mx-auto animate-scale-in" style={{ animationDelay: '0.7s' }}>
            <div className="bg-orange-500/10 backdrop-blur-sm border border-orange-500/30 rounded-xl p-6 hover:scale-105 transition-transform duration-300">
              <div className="flex items-center justify-center gap-2 mb-2">
                <span className="text-orange-400 text-lg">💡</span>
                <span className="text-orange-300 text-sm font-semibold" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)' }}>
                  Pro Tip
                </span>
              </div>
              <p className="text-orange-200 text-sm" style={{ textShadow: '1px 1px 2px rgba(0,0,0,0.8)' }}>
                Images start being in color around 1950
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
};

export default StatsSection;
