CREATE TABLE IF NOT EXISTS public.image_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    image_id TEXT NOT NULL,
    round_id TEXT NOT NULL,
    image_accuracy INT NOT NULL CHECK (image_accuracy >= 0 AND image_accuracy <= 10),
    description_accurate BOOLEAN,
    location_accurate BOOLEAN,
    date_accurate BOOLEAN,
    comment TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (user_id, round_id)
);

ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS username TEXT;
ALTER TABLE public.profiles ADD COLUMN IF NOT EXISTS earned_badges JSONB;

CREATE TABLE IF NOT EXISTS public.badges (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    description TEXT,
    icon_url TEXT,
    criteria JSONB
);

CREATE TABLE IF NOT EXISTS public.round_hints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    round_id UUID NOT NULL,
    hint_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE(user_id, round_id, hint_id)
);
