// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jghesmrwhegaotbztrhr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpnaGVzbXJ3aGVnYW90Ynp0cmhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ0MzAwMDEsImV4cCI6MjA2MDAwNjAwMX0.C-zSGAiZAIbvKh9vNb2_s3DHogSzSKImLkRbjr_h5xI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Intercept fetch to strip redirect_to from signup if present (to avoid 500s when redirect isn't whitelisted)
const originalFetch = window.fetch.bind(window);
const interceptFetch: typeof fetch = async (input: RequestInfo | URL, init?: RequestInit) => {
  try {
    const makeRequest = (urlStr: string) => originalFetch(urlStr, init);
    if (typeof input === 'string') {
      if (input.includes('/auth/v1/signup') && input.includes('redirect_to=')) {
        const url = new URL(input);
        url.searchParams.delete('redirect_to');
        console.debug('[supabase] Stripped redirect_to from signup request (string URL)');
        return makeRequest(url.toString());
      }
      return originalFetch(input, init);
    }
    if (input instanceof URL) {
      if (input.toString().includes('/auth/v1/signup') && input.searchParams.has('redirect_to')) {
        const url = new URL(input.toString());
        url.searchParams.delete('redirect_to');
        console.debug('[supabase] Stripped redirect_to from signup request (URL instance)');
        return makeRequest(url.toString());
      }
      return originalFetch(input, init);
    }
    // Request object case
    const req = input as Request;
    const href = req.url;
    if (href.includes('/auth/v1/signup') && href.includes('redirect_to=')) {
      const url = new URL(href);
      url.searchParams.delete('redirect_to');
      console.debug('[supabase] Stripped redirect_to from signup request (Request object)');
      return originalFetch(url.toString(), init ?? { method: req.method, headers: req.headers });
    }
    return originalFetch(input, init);
  } catch (e) {
    // Fallback to original if anything goes wrong
    return originalFetch(input as any, init);
  }
};

// Force global override to catch any internal usage
try {
  // Only override in browser contexts
  if (typeof window !== 'undefined' && typeof window.fetch === 'function') {
    window.fetch = interceptFetch as any;
  }
} catch {
  // ignore
}

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    storageKey: 'supabase.auth.token',
    storage: {
      getItem: (key) => {
        try {
          const remember = (() => {
            if (sessionStorage.getItem('auth.remember') === 'false') return false;
            const v = localStorage.getItem('auth.remember');
            return v === null ? true : v === 'true';
          })();
          const store = remember ? localStorage : sessionStorage;
          return store.getItem(key);
        } catch {
          return localStorage.getItem(key);
        }
      },
      setItem: (key, value) => {
        try {
          const remember = (() => {
            if (sessionStorage.getItem('auth.remember') === 'false') return false;
            const v = localStorage.getItem('auth.remember');
            return v === null ? true : v === 'true';
          })();
          const store = remember ? localStorage : sessionStorage;
          store.setItem(key, value);
          // Cross-subdomain cookie: persistent if remembered, session-only otherwise
          const base = `${key}=${value};domain=.guess-history.com;path=/;secure;samesite=lax`;
          document.cookie = remember ? `${base};max-age=${60 * 60 * 24 * 7}` : base;
        } catch {
          localStorage.setItem(key, value);
          document.cookie = `${key}=${value};domain=.guess-history.com;path=/;max-age=${60 * 60 * 24 * 7};secure;samesite=lax`;
        }
      },
      removeItem: (key) => {
        try {
          // Remove from both to be safe
          localStorage.removeItem(key);
          sessionStorage.removeItem(key);
          // Remove cookie by setting expiry in the past
          document.cookie = `${key}=;domain=.guess-history.com;path=/;max-age=0;secure;samesite=lax`;
        } catch {
          localStorage.removeItem(key);
          document.cookie = `${key}=;domain=.guess-history.com;path=/;max-age=0;secure;samesite=lax`;
        }
      }
    }
  },
  global: {
    fetch: interceptFetch,
  }
});